ssh_authorized_keys:
# - ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB...
- github:grengojbo
write_files:
- encoding: ""
  content: |-
    rc_logger="YES"
    #rc_log_path="/var/log/rc.log"
  owner: root
  path: /etc/rc.conf
  permissions: '0644'
- encoding: ""
  content: |-
    [General]
    NetworkInterfaceBlacklist=veth
    PreferredTechnologies=ethernet
    FallbackNameservers=8.8.8.8
  owner: root
  path: /etc/connman/main.conf
  permissions: '0644'
- encoding: ""
  content: |-
    #!/bin/sh
    ip route add 192.168.193.0/24 via 192.168.192.1
    ip route add 192.168.170/24 via 192.168.192.254
    ip route add 192.168.167/24 via 192.168.192.254
    ip route add 192.168.166/24 via 192.168.192.254
    ip route add 192.168.168/24 via 192.168.192.254
  owner: root
  path: /etc/network/if-up.d/ip150
  permissions: '0775'
- encoding: ""
  content: |-
    . /etc/profile.d/bash_completion.sh
    # kubectl completion bash >/etc/bash_completion.d/kubectl
    source <(kubectl completion bash)
    alias k=kubectl
    complete -F __start_kubectl k
  owner: rancher
  path: /home/rancher/.bash_profile
  permissions: '0644'
- encoding: ""
  content: |-
    # /etc/inittab

    ::sysinit:/sbin/openrc sysinit
    ::sysinit:/sbin/openrc boot
    ::wait:/sbin/openrc default

    # Stuff to do for the 3-finger salute
    ::ctrlaltdel:/sbin/reboot

    # Stuff to do before rebooting
    ::shutdown:/sbin/openrc shutdown

    # Dynamically appended getty stuff
    tty1::respawn:/sbin/getty 38400 tty1
    tty2::respawn:/sbin/getty 38400 tty2
  owner: root
  path: /etc/inittab
  permissions: '0664'
# - encoding: ""
#   content: |-
#     #!/bin/bash
#     echo hello, local service start
#   owner: root
#   path: /etc/local.d/example.start
#   permissions: '0755'
# hostname: myhost
#
# /Block start Drive and RAID mounting documentation
# write_files:
#   - path: /etc/fstab
#     content: |-
#       /dev/cdrom    /media/cdrom      iso9660 noauto,ro 0 0
#       /dev/usbdisk  /media/usb        vfat    noauto,ro 0 0
#       /dev/md0      /var/lib/longhorn ext4    noatime,nodiratime,data=writeback,nofail 0 0
# boot_cmd:
#   - mdadm --assemble --scan
# run_cmd:
#  - mkdir -p /var/lib/longhorn
# /Block end
#
# init_cmd:
# - "echo hello, init command"
boot_cmd:
- "echo hello, boot command"
- /usr/bin/growpart /dev/sda 1
- /usr/sbin/resize2fs /dev/sda1
#- mkdir -p /var/lib/longhorn
# - "resize2fs /dev/sda1"
run_cmd:
- "echo hello, run command"
- ip route add 192.168.193.0/24 via 192.168.192.1
#- ip link set eth1 mtu 1400
# - "rc-service iscsid stop"
# - "rc-service wpa_supplicant stop"
k3os:
  # data_sources:
  # - aws
  # - cdrom
  # modules:
  # - kvm
  # - nvme
  # sysctl:
  #   kernel.printk: "4 4 1 7"
  #   kernel.kptr_restrict: "1"
  # dns_nameservers:
  # - 8.8.8.8
  # - 1.1.1.1
  # ntp_servers:
  # - 0.us.pool.ntp.org
  # - 1.us.pool.ntp.org
  # wifi:
  # - name: home
  #   passphrase: mypassword
  # - name: nothome
  #   passphrase: somethingelse
  # password: rancher
  # server_url: https://someserver:6443
  # token: TOKEN_VALUE
  labels:
    region: hz-server-2
    # somekey: somevalue
  k3s_args:
  - server
  #- "--disable-agent"
  # - "--cluster-domain=k3s.dus.waigant.io"
  # - "--tls-san *.k3s.dus.waigant.io"
  #- "--disable=traefik"
  #- "--disable=servicelb"
  - "--secrets-encryption"
  - "--node-name=$(hostname -f)"
  # - "--flannel-backend=none"
  # - "--datastore-endpoint=mysql://root:root@tcp(localhost:3306)/k3s"
  # environment:
  #   http_proxy: http://myserver
  #   https_proxy: http://myserver
  # taints:
  # - CriticalAddonsOnly=true:NoExecute
  # - key1=value1:NoExecute
